[config]
[templates.hypr]
input_path  = "~/.config/matugen/templates/hypr.lua"
output_path = "~/.config/hypr/theme.lua"
[templates.kitty]
input_path  = "~/.config/matugen/templates/kitty.conf"
output_path = "~/.config/kitty/theme.conf"
[templates.waybar]
input_path  = "~/.config/matugen/templates/waybar.css"
output_path = "~/.config/waybar/colors.css"
[templates.swaync]
input_path  = "~/.config/matugen/templates/swaync.css"
output_path = "~/.config/swaync/colors.css"
[templates.rofi]
input_path  = "~/.config/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/colors.rasi"
[templates.zellij]
input_path  = "~/.config/matugen/templates/zellij.kdl"
output_path = "~/.config/zellij/themes/theme.kdl"
[templates.yazi]
input_path  = "~/.config/matugen/templates/yazi.toml"
output_path = "~/.config/yazi/theme.toml"
[templates.btop]
input_path  = "~/.config/matugen/templates/btop.theme"
output_path = "~/.config/btop/themes/theme.theme"
[templates.qt6ct]
input_path  = "~/.config/matugen/templates/qt6ct.conf"
output_path = "~/.config/qt6ct/colors/theme.conf"
